
name: shell

on: [push, workflow_dispatch]

jobs:
  runshell:
    runs-on: macos-latest
    name: Start a freebsd shell
    steps:
    - name: Sleep
      run: sleep 5
    - uses: neilpang/debugger-action@master

